name: Generate New Images

on:
  schedule: 
    - cron: '05 00 * * *'
  workflow_dispatch:
    inputs:
      beauforceupdateimg:
        description: 'Force Update Images'
        default: false
        type: boolean
        required: false


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Run main
      run: python beau_progress/generate_img.py
      env: 
        BEAUFORCEUPDATEIMG: ${{ inputs.beauforceupdateimg }}
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'beau_progress/*'
        message: 'Generate New Stats'
        default_author: github_actions
        push: true
